object_permissions_m2m/urls.py
import os

from django.conf.urls.defaults import url, patterns

urlpatterns = patterns('object_permissions_m2m.views.groups',
    url(r'^group/(?P<id>\d+)/permissions/?$','user_permissions', name="group-permissions"),
    url(r'^group/(?P<id>\d+)/permissions/user/(?P<user_id>\d+)/?$','user_permissions', name="group-user-permissions"),
    url(r'^group/(?P<id>\d+)/permissions/all/?$','all_permissions', name="group-all-permissions"),
)

urlpatterns += patterns('object_permissions_m2m.views.permissions',
    # List all perms for a given user
    url(r'^user/(?P<id>\d+)/permissions/all/?$','all_permissions', name="user-all-permissions"),
    
    # add permissions on an object
    url(r'^user/(?P<user_id>\d+)/permissions/(?P<class_name>\w+)/?$','view_obj_permissions', name="user-add-permissions"),
    url(r'^group/(?P<group_id>\d+)/permissions/(?P<class_name>\w+)/?$','view_obj_permissions', name="group-add-permissions"),
    
    # edit permissions on an object
    url(r'^user/(?P<user_id>\d+)/permissions/(?P<class_name>\w+)/(?P<obj_id>\d+)/?$', \
        'view_obj_permissions', name="user-edit-permissions"),
    url(r'^group/(?P<group_id>\d+)/permissions/(?P<class_name>\w+)/(?P<obj_id>\d+)?$', \
        'view_obj_permissions', name="group-edit-permissions"),
)

urlpatterns += patterns('object_permissions_m2m.views.widgets',
    url(r'^user/search/?$', 'search_users', name='user-search')
)

#The following is used to serve up local media files like images
root = '%s/media' % os.path.dirname(os.path.realpath(__file__))
urlpatterns += patterns('',
    (r'^object_permissions_media/(?P<path>.*)', 'django.views.static.serve',\
     {'document_root':  root}),
)

object_permissions_m2m/views/permissions.py
import json

from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext

from object_permissions_m2m import get_user_perms, get_group_perms, \
    get_model_perms, get_users, get_groups, get_class
from object_permissions_m2m.models import Group
from object_permissions_m2m.signals import view_add_user, view_remove_user, \
    view_edit_user


class ObjectPermissionForm(forms.Form):
    """
    Form used for editing permissions
    """
    permissions = forms.MultipleChoiceField(required=False,
                                            widget=forms.CheckboxSelectMultiple)
    user = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    group = forms.ModelChoiceField(queryset=Group.objects.all(),
                                   required=False)
    obj = forms.ModelChoiceField(queryset=None)
    
    # dictionary used for caching the choices for specific models
    choices = {}
    
    def __init__(self, model, *args, **kwargs):
        """
        @param model - the object being granted permissions
        """
        super(ObjectPermissionForm, self).__init__(*args, **kwargs)
        
        self.model = model
        self.fields['obj'].queryset = model.objects.all()
        self.fields['obj'].label = model.__name__
        self.fields['permissions'].choices = self.get_choices(model)

    @classmethod
    def get_choices(cls, model):
        """
        helper method for getting choices for a model.  This method uses an
        internal cache to store the choices.
        
        @param model - Model class to fetch choices for
        """
        try: 
            return ObjectPermissionForm.choices[model]
        except KeyError:
            # choices weren't built yet.
            choices = []
            model_perms = get_model_perms(model)
            
            for perm, params in model_perms.items():
                display = params.copy()
                if 'label' not in display:
                    display['label'] = perm
                choices.append((perm, display))
            ObjectPermissionForm.choices[model] = choices
            return choices

    def clean(self):
        """
        validates:
            * mutual exclusivity of user and group
            * a user or group is always selected and set to 'grantee'
        """
        data = self.cleaned_data
        user = data.get('user')
        group = data.get('group')
        if not (user or group) or (user and group):
            raise forms.ValidationError('Choose a group or user')
        
        # add whichever object was selected
        data['grantee'] = user if user else group
        return data
    
    def update_perms(self):
        """
        updates perms for the user based on values passed in
            * grant all perms selected in the form.  Revoke all
            * other available perms that were not selected.
            
        @return list of perms the user now possesses
        """
        perms = self.cleaned_data['permissions']
        grantee = self.cleaned_data['grantee']
        obj = self.cleaned_data['obj']
        grantee.set_perms(perms, obj)
        return perms
    

class ObjectPermissionFormNewUsers(ObjectPermissionForm):
    """
    A subclass of permission form that enforces an addtional rule that new users
    must be granted at least one permission.  This is used for objects that
    determine group membership (e.g. listing users with acccess) based on who
    has permissions.
    
    This is different from objects that grant inherent permissions through a
    different membership relationship (e.g. Users in a Group inherit perms)
    """
    
    def clean(self):
        data = super(ObjectPermissionFormNewUsers, self).clean()
        
        if 'grantee' in data:
            grantee = data['grantee']
            perms = data['permissions']
            
            if 'obj' in data:
                # if grantee does not have permissions, then this is a new user:
                #    - permissions must be selected
                old_perms = grantee.get_perms(data['obj'], groups=False)
                if old_perms:
                    # not new, has perms already
                    data['new'] = False
                    
                elif not perms:
                    # new, doesn't have perms specified
                    msg = """You must grant at least 1 permission for new users and groups"""
                    self._errors["permissions"] = self.error_class([msg])
                    
                else:
                    # new, perms specified
                    data['new'] = True
            
            else:
                # no obj specified, must be adding a new object.  Still need to
                # verify perms
                if not perms:
                    msg = """You must grant at least 1 permission for new users and groups"""
                    self._errors["permissions"] = self.error_class([msg])
        
        return data


def view_users(request, object_, url, \
               template='object_permissions/permissions/users.html', rest=False):
    """
    Generic view for rendering a list of Users who have permissions on an
    object.
    
    This view does not perform any validation of user permissions, that should
    be done in another view which calls this view for display
    
    @param request: HttpRequest
    @param object_: object to list Users and Groups for
    @param url: base url for editing permissions
    @param template: template for rendering User/Group list.
    """
    users = get_users(object_, groups=False)
    groups = get_groups(object_)

    if not rest:
        return render_to_response(template, \
            {'object': object_,
             'users':users,
             'groups':groups,
             'url':url},
        context_instance=RequestContext(request),
    )
    else:
        return {'object': object_,
             'users':users,
             'groups':groups,
             'url':url}


def view_permissions(request, obj, url, user_id=None, group_id=None,
                user_template='object_permissions/permissions/user_row.html',
                group_template='object_permissions/permissions/group_row.html'
                ):
    """
    Update a User or Group permissions on an object.  This is a generic view
    intended to be used for editing permissions on any object.  It must be
    configured with a model and url.  It may also be customized by adding custom
    templates or changing the pk field.
    
    @param obj: object permissions are being set on
    @param url: name of url being edited
    @param user_id: ID of User being edited
    @param group_id: ID of Group being edited
    @param user_template: template used to render user rows
    @param group_template: template used to render group rows
    """
    if request.method == 'POST':
        form = ObjectPermissionFormNewUsers(obj.__class__, request.POST)
        if form.is_valid():
            data = form.cleaned_data
            form_user = form.cleaned_data['user']
            group = form.cleaned_data['group']
            edited_user = form_user if form_user else group
            
            if form.update_perms():
                # send correct signal based on new or edited user
                if data['new']:
                    view_add_user.send(sender=obj.__class__,
                                       editor=request.user,
                                       user=edited_user, obj=obj)
                else:
                    view_edit_user.send(sender=obj.__class__,
                                        editor=request.user,
                                        user=edited_user, obj=obj)
                
                # return html to replace existing user row
                if form_user:
                    return render_to_response(user_template,
                                {'object':obj, 'user_detail':form_user, 'url':url},
                                context_instance=RequestContext(request))
                else:
                    return render_to_response(group_template,
                                {'object':obj, 'group':group, 'url':url},
                                context_instance=RequestContext(request))
                
            else:
                # no permissions, send ajax response to remove user
                view_remove_user.send(sender=obj.__class__,
                                      editor=request.user, user=edited_user,
                                      obj=obj)
                id = ('"user_%d"' if form_user else '"group_%d"')%edited_user.pk
                return HttpResponse(id, mimetype='application/json')

        # error in form return ajax response
        content = json.dumps(form.errors)
        return HttpResponse(content, mimetype='application/json')

    if user_id:
        form_user = get_object_or_404(User, id=user_id)
        data = {'permissions':get_user_perms(form_user, obj, False),
                'user':user_id, 'obj':obj}
    elif group_id:
        group = get_object_or_404(Group, id=group_id)
        data = {'permissions':get_group_perms(group, obj),
                'group':group_id, 'obj':obj}
    else:
        data = {}
        
    form = ObjectPermissionFormNewUsers(obj.__class__, data)
    
    return render_to_response('object_permissions/permissions/form.html',
                {'form':form, 'obj':obj, 'user_id':user_id,
                'group_id':group_id, 'url':url},
               context_instance=RequestContext(request))


@login_required
def view_obj_permissions(request, class_name, obj_id=None,
    user_id=None, group_id=None,

object_permissions_m2m/templates/object_permissions/permissions/form.html
{% comment  %} Form for setting user permissions on an object {% endcomment %}

<script type="text/javascript" src="{{SITE_ROOT}}/object_permissions_media/js/autocomplete_user_search.js"></script>
{# Only run autocomplete script if a user or group needs to be selected #}
{% if user_id or group_id %}
    <script> </script>
{% else %}
    <script>
         $(function(){
            autocomplete_user_search($("#id_user"),'{% url user-search %}',{'group':$("#id_group")});
         });
    </script>
{% endif %}

<form class="object_permissions_form" method="post" action="{{url}}">
    <ul id="errors"></ul>
    <table>
    {# Only show object select when an object hasn't been preselected #}
    {% if obj %}
        <input type="hidden" name="obj" value="{{obj.pk|default:''}}"/>
    {% else %}
        <tr><td>{{form.obj.label}}</td><td>{{form.obj}}</td></tr>
    {% endif %}

    {# only show user/group when one hasn't been preselected #}
    {% if user_id or group_id %}
        <input type="hidden" name="user" value="{{user_id|default:''}}"/>
        <input type="hidden" name="group" value="{{group_id|default:''}}"/>
    {% else %}
        <tr class="user"><td><b>{{form.user.label}}:</b></td><td>{{form.user}}</td></tr>
        <tr class="group"><td><b>{{form.group.label}}:</b></td><td>{{form.group}}</td></tr>
    {% endif %}
    
        {# Manually create permissions checkboxes so we can integrate it into the table #}
        {% with form.data.permissions as data %}
        {% for permission in form.fields.permissions.choices %}
        <tr class="permission">
            <td class="input">
                <input id="id_permissions_{{forloop.counter0}}" name="permissions" type="checkbox" value="{{permission.0}}"
                {%if permission.0 in data %}checked{%endif%}
                />
                <label for="id_permissions">{{permission.1.label}}{% if permission.1.description %}:{%endif%}</label>
            </td>
            <td>{{permission.1.description}}</td>
        </tr>
        {% endfor %}
        {% endwith %}
    </table>
    <input type="submit" class="submit" value="Save"/>
</form>

object_permissions_m2m/templates/object_permissions/permissions/group_row.html
{% load object_permission_tags %}

<tr id="group_{{group.id}}" class="group">
<td class="name">
    {% if user|group_admin:group %}
        {% permalink group group.name %}
    {% else %}
        {{ group.name }}
    {% endif %}
</td>
<td class="permissions">
    <a href="{{url}}/group/{{group.id}}" class="permissions" title="click to edit">
    {% for permission in group|permissions:object %}
        {{permission}}{%if not forloop.last%}, {%endif%}
    {% empty %}
    <span class="none">None</span>
    {% endfor %}
    </a>
</td>
{%block table_cells%}{%endblock%}
<td><div class="delete" title="delete"></div></td>
</tr>

object_permissions_m2m/templates/object_permissions/permissions/object_row.html
{% load object_permission_tags %}
<tr id="{{class_name}}_{{obj.pk}}">
    <td class="obj">{% permalink obj %}</td>
    <td class="perms">
        {% if persona|is_user %}
            <a href="{% url user-edit-permissions persona.pk class_name obj.pk %}">
        {% else %}
            <a href="{% url group-edit-permissions persona.pk class_name obj.pk %}">
        {% endif %}
        {% for permission in persona|permissions:obj %}
            {{permission}}{%if not forloop.last%}, {%endif%}
        {% endfor %}
       </a>
    </td>
    <td>
        <div class="icon delete">
            {% if persona|is_user %}
                <a href="{% url user-edit-permissions persona.pk class_name obj.pk %}">
            {% else %}
                <a href="{% url group-edit-permissions persona.pk class_name obj.pk %}">
            {% endif %}
        </a></div>
    </td>
</tr>

object_permissions_m2m/templates/object_permissions/permissions/objects.html
{% load object_permission_tags %}

<style>
    table.permissions {margin-bottom:25px !important;}
    table.permissions td, table.permissions th {text-align:left !important;}
    table.permissions td.obj {color:black; width:200px;}
    table.permissions td.perms {color:#555;}
</style>

{% for class_name, objs in perm_dict.items %}
    {% if persona|is_user %}
        <a class="button add permission" href="{% url user-add-permissions persona.pk class_name %}">
    {% else %}
        <a class="button add permission" href="{% url group-add-permissions persona.pk class_name %}">
    {% endif %}
        Add {{class_name}}</a>
    <table id="{{class_name}}" class="permissions object_permissions">
        <tr><th colspan="100%">{{class_name}}</th></tr>
        {% for obj in objs %}
            {% include "object_permissions/permissions/object_row.html" %}
        {% endfor %}
    </table>
{% endfor %}

<script type="text/javascript">
    var is_user = {% if persona|is_user %}true{% else %}false{% endif %};
    var persona_pk = {{persona.pk}};
</script>
<script type="text/javascript" src="{{SITE_ROOT}}/object_permissions_media/js/jquery.form.js"></script>
<script type="text/javascript" src="{{SITE_ROOT}}/object_permissions_media/js/objects.js"></script>

object_permissions_m2m/templates/object_permissions/permissions/table.html
<div id="add_user" class="button add">Add User</div>
<table id="op_users">
    <tr>
        <th>Name</th>
        <th>Permissions</th>
        {% block table_headers%}{% endblock %}
        <th></th>
    </tr>
    {% for user_detail in users %}
        {%block user_row%}{% include "object_permissions/permissions/user_row.html" %}{%endblock%}
    {% endfor %}
    {% for group in groups %}
        {%block group_row%}{% include "object_permissions/permissions/group_row.html" %}{%endblock%}
    {% endfor %}
</table>

object_permissions_m2m/templates/object_permissions/permissions/user_row.html
{% load object_permission_tags %}
<tr id="user_{{user_detail.id}}" class="user">
<td class="name">
    {% if user.is_superuser %}
        {% permalink user_detail user_detail.username %}
    {% else %}
        {{ user_detail.username }}
    {% endif %}
</td>
<td class="permissions">
    <a href="{{url}}/user/{{user_detail.id}}" class="permissions" title="click to edit">
    {% for permission in user_detail|permissions:object %}
        {{permission}}{%if not forloop.last%}, {%endif%}
    {% empty %}
    <span class="none">None</span>
    {% endfor %}
    </a>
</td>
{%block table_cells%}{%endblock%}
<td><div class="delete" title="delete"></div></td>
</tr>

object_permissions_m2m/templates/object_permissions/permissions/users.html
<link rel="stylesheet" type="text/css" href="{{SITE_ROOT}}/object_permissions_media/css/form.css"/>
<script type="text/javascript">var user_url = "{{url}}"; var obj_id = {{object.pk}};</script>
<script type="text/javascript" src="{{SITE_ROOT}}/object_permissions_media/js/users.js"></script>
<script type="text/javascript" src="{{SITE_ROOT}}/object_permissions_media/js/jquery.form.js"></script>
{% block head %}{% endblock %}

<div id="add_user" class="button add">Add User</div>
<table id="op_users">
    <tr>
        <th>Name</th>
        <th>Permissions</th>
        {% block table_headers%}{% endblock %}
        <th></th>
    </tr>
    {% for user_detail in users %}
        {%block user_row%}{% include "object_permissions/permissions/user_row.html" %}{%endblock%}
    {% endfor %}
    {% for group in groups %}
        {%block group_row%}{% include "object_permissions/permissions/group_row.html" %}{%endblock%}
    {% endfor %}
</table>